"""initial schema

Revision ID: 0001_initial
Revises: 
Create Date: 2026-08-01 17:16:13.088017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_initial'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('contact', sa.String(length=200), nullable=True),
    sa.Column('sla_target_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('CAMERA', 'NVR', 'SWITCH', name='device_type'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('make', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('rtsp_url', sa.String(length=500), nullable=True),
    sa.Column('onvif_url', sa.String(length=500), nullable=True),
    sa.Column('parent_nvr_id', sa.Integer(), nullable=True),
    sa.Column('channel_no', sa.Integer(), nullable=True),
    sa.Column('building', sa.String(length=200), nullable=True),
    sa.Column('zone', sa.String(length=200), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('installation_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('criticality', sa.Enum('CRITICAL', 'HIGH', 'NORMAL', name='criticality'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('current_state', sa.Enum('UP', 'DEGRADED', 'DOWN', 'MAINTENANCE', 'UNKNOWN', name='device_state'), nullable=False),
    sa.Column('ping_interval_s', sa.Integer(), nullable=False),
    sa.Column('rtsp_interval_s', sa.Integer(), nullable=False),
    sa.Column('nvr_interval_s', sa.Integer(), nullable=False),
    sa.Column('image_interval_s', sa.Integer(), nullable=False),
    sa.Column('next_ping_check_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_rtsp_check_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_nvr_check_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_image_check_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_nvr_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_building'), 'devices', ['building'], unique=False)
    op.create_index(op.f('ix_devices_ip'), 'devices', ['ip'], unique=False)
    op.create_index(op.f('ix_devices_vendor_id'), 'devices', ['vendor_id'], unique=False)
    op.create_index(op.f('ix_devices_zone'), 'devices', ['zone'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'SECURITY_OFFICER', 'TECHNICIAN', 'VIEWER', name='user_role'), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.String(length=64), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.Enum('CRITICAL', 'WARNING', 'INFO', name='alert_severity'), nullable=False),
    sa.Column('state', sa.Enum('OPEN', 'ACKED', 'CLOSED', name='alert_state'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('acked_by', sa.Integer(), nullable=True),
    sa.Column('acked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['acked_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_device_id'), 'alerts', ['device_id'], unique=False)
    op.create_index(op.f('ix_alerts_group_id'), 'alerts', ['group_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=100), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('detail_jsonb', sa.JSON(), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=200), nullable=True),
    sa.Column('secret_encrypted', sa.String(length=1000), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id')
    )
    op.create_table('maintenance_windows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope_type', sa.Enum('DEVICE', 'GROUP', 'BUILDING', 'CAMPUS', name='maintenance_scope'), nullable=False),
    sa.Column('scope_id', sa.Integer(), nullable=True),
    sa.Column('scope_building', sa.String(length=200), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rrule', sa.String(length=500), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('value_jsonb', sa.JSON(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('status_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('old_state', sa.Enum('UP', 'DEGRADED', 'DOWN', 'MAINTENANCE', 'UNKNOWN', name='device_state'), nullable=False),
    sa.Column('new_state', sa.Enum('UP', 'DEGRADED', 'DOWN', 'MAINTENANCE', 'UNKNOWN', name='device_state'), nullable=False),
    sa.Column('cause', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('downtime_seconds', sa.Integer(), nullable=True),
    sa.Column('suppressed_by_parent', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_status_events_device_id'), 'status_events', ['device_id'], unique=False)
    op.create_table('escalations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('fired_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notified_user_ids', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_escalations_alert_id'), 'escalations', ['alert_id'], unique=False)
    op.create_table('notification_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Enum('EMAIL', 'SMS', 'WHATSAPP', name='notification_channel'), nullable=False),
    sa.Column('recipient', sa.String(length=320), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', 'SKIPPED_NOT_CONFIGURED', name='notification_status'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_log_alert_id'), 'notification_log', ['alert_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_log_alert_id'), table_name='notification_log')
    op.drop_table('notification_log')
    op.drop_index(op.f('ix_escalations_alert_id'), table_name='escalations')
    op.drop_table('escalations')
    op.drop_index(op.f('ix_status_events_device_id'), table_name='status_events')
    op.drop_table('status_events')
    op.drop_table('settings')
    op.drop_table('maintenance_windows')
    op.drop_table('credentials')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_alerts_group_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_device_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_devices_zone'), table_name='devices')
    op.drop_index(op.f('ix_devices_vendor_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_ip'), table_name='devices')
    op.drop_index(op.f('ix_devices_building'), table_name='devices')
    op.drop_table('devices')
    op.drop_table('vendors')
    # ### end Alembic commands ###
